In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

from utils.file_utils import get_cleaned_tickets_as_df

In [2]:
tickets_df = get_cleaned_tickets_as_df(path="./data/cleaned_tickets_v4.csv")
# tickets_df = tickets_df[tickets_df["sent_by"]=="Customer"]
tickets_df

,ticket_number,message,tags
0,21,Hi! What is your pricing? Can I talk with some...,Sales
1,22,"Hi, how much is Atlas? Looks like it, yeah.",Sales
2,30,hey not super urgent but fyi in ramp bank you ...,Feature Request
3,39,some minor feedback - i seem to need to sign i...,Feature Request
4,42,Hello! Just came across your site: do you offe...,Feature Request
...,...,...,...
744,1522,"Good morning, everyone. A customer contacted u...",Bug
745,1523,Hey quick question - we are figuring out how t...,Feature Request
746,1524,Hi - I'm running into an issue where there are...,Bug
747,1525,Hey @Rahul Asati!It looks like we are still ge...,Bug
748,1528,"Good morning, everyone. Atlas is running quite...",Bug

In [26]:
!python3 -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.7.1
  Using cached https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl (12.8 MB)
Requirement already satisfied: spacy<3.8.0,>=3.7.2 in ./venv/lib/python3.11/site-packages (from en-core-web-sm==3.7.1) (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.9)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.4.8)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.12.3)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.66.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.7.4)
Requirement already satisfied: jinja2 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.1.4)
Requirement already satisfied: setuptools in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (70.1.0)
Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (24.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.4.0)
Requirement already satisfied: numpy>=1.19.0 in ./venv/lib/python3.11/site-packages (from spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.26.4)
Requirement already satisfied: language-data>=1.2 in ./venv/lib/python3.11/site-packages (from langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in ./venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.0)
Requirement already satisfied: pydantic-core==2.18.4 in ./venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.18.4)
Requirement already satisfied: typing-extensions>=4.6.1 in ./venv/lib/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2024.6.2)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in ./venv/lib/python3.11/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in ./venv/lib/python3.11/site-packages (from thinc<8.3.0,>=8.2.2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.5)
Requirement already satisfied: click>=8.0.0 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./venv/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (13.7.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in ./venv/lib/python3.11/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.18.1)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in ./venv/lib/python3.11/site-packages (from weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (7.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.11/site-packages (from jinja2->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.1.5)
Requirement already satisfied: marisa-trie>=0.7.7 in ./venv/lib/python3.11/site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.2.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./venv/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./venv/lib/python3.11/site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (2.18.0)
Requirement already satisfied: wrapt in ./venv/lib/python3.11/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (1.16.0)
Requirement already satisfied: mdurl~=0.1 in ./venv/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy<3.8.0,>=3.7.2->en-core-web-sm==3.7.1) (0.1.2)

[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: pip install --upgrade pip
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [27]:
from utils.text_utils import clean_text, lemmmatize_text, get_pos_tags

tickets_df["message_cleaned"] = tickets_df.message.apply(clean_text)
tickets_df["message_lemmatized"] = tickets_df.message_cleaned.apply(lemmmatize_text)
tickets_df["message_pos"] = tickets_df.message_lemmatized.apply(get_pos_tags)
tickets_df

,ticket_number,message,tags,message_cleaned,message_lemmatized,message_pos
0,21,Hi! What is your pricing? Can I talk with some...,Sales,hi what is your pricing can i talk with someon...,hi what be your pricing can I talk with someon...,pricing someone phone call
1,22,"Hi, how much is Atlas? Looks like it, yeah.",Sales,hi how much is atlas looks like it yeah,hi how much be atlas look like it yeah,look
2,30,hey not super urgent but fyi in ramp bank you ...,Feature Request,hey not super urgent but fyi in ramp bank you ...,hey not super urgent but fyi in ramp bank you ...,hey urgent fyi bank merriam webster screenshot...
3,39,some minor feedback - i seem to need to sign i...,Feature Request,some minor feedback i seem to need to sign in...,some minor feedback I seem to need to sign i...,feedback service thank feedback adam session t...
4,42,Hello! Just came across your site: do you offe...,Feature Request,hello just came across your site do you offer ...,hello just come across your site do you offer ...,hello site control moment let support agent fe...
...,...,...,...,...,...,...
744,1522,"Good morning, everyone. A customer contacted u...",Bug,good morning everyone a customer contacted us ...,good morning everyone a customer contact we vi...,morning everyone customer contact today ticket...
745,1523,Hey quick question - we are figuring out how t...,Feature Request,hey quick question we are figuring out how to...,hey quick question we be figure out how to s...,hey question support license hour sla escalati...
746,1524,Hi - I'm running into an issue where there are...,Bug,hi im running into an issue where there are c...,hi I m run into an issue where there be chat...,hi issue chatticket filter michael call suppor...
747,1525,Hey @Rahul Asati!It looks like we are still ge...,Bug,hey rahul asatiit looks like we are still gett...,hey rahul asatiit look like we be still get gi...,hey email receive hey yahalomiseem mail format...
748,1528,"Good morning, everyone. Atlas is running quite...",Bug,good morning everyone atlas is running quite s...,good morning everyone atlas be run quite slow ...,morning everyone atlas today page issue team t...

In [28]:
df_clean = tickets_df[["message_pos", "tags"]]

# reverse_topic_mapping = {
#     "Spam": "0",
#     "Sales": "1",
#     "Feature Request": "2",
#     "Bug": "3",
#     "Product Question": "4",
# }
# # Replace Topics with Topic Names
# df_clean["tags"] = df_clean["tags"].map(reverse_topic_mapping)

df_clean.head()

                                         message_pos             tags
0                         pricing someone phone call            Sales
1                                               look            Sales
2  hey urgent fyi bank merriam webster screenshot...  Feature Request
3  feedback service thank feedback adam session t...  Feature Request
4  hello site control moment let support agent fe...  Feature Request

In [29]:
# Split data into features and labels
X = df_clean["message_pos"]
y = df_clean["tags"]

# Split into training and testing sets (note: with very small dataset, train/test split is just for demonstration)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42
)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

# Build a pipeline
pipeline = Pipeline(
    [
        # ("count_vectorizer", CountVectorizer()),
        ("tfidf", TfidfVectorizer(min_df=2, max_df=0.95, stop_words="english")),
        ("classifier", LogisticRegression(random_state=40, solver="liblinear")),
    ]
)

# Train the model
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the model
print(pipeline.score(X_train, y_train))
print(pipeline.score(X_test, y_test))
print(classification_report(y_test, y_pred))

0.8041543026706232
0.49333333333333335
                  precision    recall  f1-score   support

             Bug       0.50      0.61      0.55        18
 Feature Request       0.43      0.56      0.49        18
Product Question       0.50      0.40      0.44        25
           Sales       0.60      0.50      0.55        12
            Spam       0.00      0.00      0.00         2

        accuracy                           0.49        75
       macro avg       0.41      0.41      0.41        75
    weighted avg       0.49      0.49      0.48        75

/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [31]:
from sklearn.naive_bayes import MultinomialNB

# Build a pipeline
pipeline = Pipeline(
    [
        ("count_vectorizer", CountVectorizer()),
        #("tfidf", TfidfVectorizer(min_df=2, max_df=0.95, stop_words="english")),
        ("classifier", MultinomialNB()),
    ]
)

# fit model
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

print(pipeline.score(X_train, y_train))
print(pipeline.score(X_test, y_test))
print(classification_report(y_test, y_pred))

0.8367952522255193
0.49333333333333335
                  precision    recall  f1-score   support

             Bug       0.46      0.67      0.55        18
 Feature Request       0.44      0.61      0.51        18
Product Question       0.59      0.40      0.48        25
           Sales       0.60      0.25      0.35        12
            Spam       0.50      0.50      0.50         2

        accuracy                           0.49        75
       macro avg       0.52      0.49      0.48        75
    weighted avg       0.52      0.49      0.48        75

In [32]:
from sklearn.tree import DecisionTreeClassifier

# Build a pipeline
pipeline = Pipeline(
    [
        ("count_vectorizer", CountVectorizer()),
        #("tfidf", TfidfVectorizer(min_df=2, max_df=0.95, stop_words="english")),
        ("classifier", DecisionTreeClassifier()),
    ]
)

# fit model
pipeline.fit(X_train, y_train)

# Predict on the test set
y_pred = pipeline.predict(X_test)

print(pipeline.score(X_train, y_train))
print(pipeline.score(X_test, y_test))
print(classification_report(y_test, y_pred))

0.9955489614243324
0.4266666666666667
                  precision    recall  f1-score   support

             Bug       0.33      0.39      0.36        18
 Feature Request       0.39      0.39      0.39        18
Product Question       0.48      0.44      0.46        25
           Sales       0.54      0.58      0.56        12
            Spam       0.00      0.00      0.00         2

        accuracy                           0.43        75
       macro avg       0.35      0.36      0.35        75
    weighted avg       0.42      0.43      0.42        75

/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/goldentown/Projects/interviews/sortify/venv/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1517: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))